Algoritmo "medidas"

Var

   medidaA, medidaB, medidaC : real
   
Inicio

   escreval("Insira os dados abaixo")
   escreva("Digite a medida A: ")
   leia(medidaA)
   
   escreva("Digite a medida B: ")
   leia(medidaB)
   
   escreva("Digite a medida C: ")
   leia(medidaC)
   
   escreval
   escreval("Área do quadrado = ", medidaA*medidaA:8:4)
   escreval("Área do triangulo = ", medidaA*medidaB/2:8:4)
   escreval("Área do trampezio = ", (medidaA+medidaB)*medidaC/2:8:4)
   
Fimalgoritmo