Algoritmo "operadora"

Var

 min : inteiro
 pagamento : real

Inicio

      escreval(" insira os valores abaixo ")
      escreva("Digite a quantidade de minutos: ")
      leia (min)
      
      pagamento <- 50
      
      se min > 100 entao
         pagamento <- pagamento + 2 * (min - 100)
      fimse
      
      escreval("Valor a pagar R$ ", pagamento:4:2)
         

         
         

      
      




Fimalgoritmo